### ISSUE TITLE
Outline collapses on Ctrl+S (Save)

### ISSUE THREAD

**Issue by ulysses4ever** [boyland/sasylf#100]
I like to have names of certain rules before me when proving. The issues is: when I unfold certain judgments in the Outline view and do a bit of proving, I have to save my work to see what the system thinks about it; at this point I press Ctrl+S to Save, which, for some reason, makes Outline refresh (seemingly), and all things that I unfolded there before is back to the initial folded state.

**Comment by boyland** [comment]
I've noticed this too. It's annoying.  Do you happen to know if green-check-mark (aka meta-zero) does the same thing?

**Comment by ulysses4ever** [comment]
I just tried, and it appears to do the same modulo saving changes: the proof script (meaning the current state of the buffer) is checked, and Outline is refreshed/collapsed.

**Comment by ulysses4ever** [comment]
It seems they are a bit different code paths after all, unfortunately. I tried to comment out these two lines:
https://github.com/boyland/sasylf/blob/master/src/org/sasylf/ProofChecker.java#L283-L284
and this fixed the issue for Ctrl+0 (aka Meta+0, aka Green Check mark), but not for Save. It'd be an improvement still if not for the caveat that Outline is not loaded on startup after this change. To force Outline re-render, you need to Ctrl+S. So I'm not sure it's a terribly good idea. Maybe Outline should be updated on Ctrl+0 as well as Ctrl+S but just needs to be smarter about preserving its state on such update. Some hacking in [ProofOutline.java](https://github.com/boyland/sasylf/blob/master/src/org/sasylf/views/ProofOutline.java) is probably required.

**Comment by boyland** [comment]
Yes, ProofOutline will need to change. Perhaps it's enough to reuse elements in the tree rather than recreate them.  When I get a chance, I'll try that.  But not informing listeners is not a recommended approach -- the outline view won't be updated even when it should change.

**Comment by ulysses4ever** [comment]
Agreed. 

I thought it may _in theory_  make sense to update Outline only on Save, not on Check Proof (that's the effect of what I mentioned above). But I don't argue for that.
