### ISSUE TITLE
Internal error on unbound variable

### ISSUE THREAD

**Issue by ulysses4ever** [boyland/sasylf#103]
[This script](https://gist.github.com/ulysses4ever/4a83c1c3f286dcae935d95e3e039e614) produces an internal error in the plugin and throws IndexOutOfBounds exception from command-line. This probably should be avoided.

(The problem is in the [unbound variable on line 177](https://gist.github.com/ulysses4ever/4a83c1c3f286dcae935d95e3e039e614).)

**Comment by boyland** [comment]
Yes.  This is a bug.  It turns out "use inversion" works terribly with the special rule.  Currently case analysis has separate code from inversion; I've had it on my long-term TODO list to refactor this duplication away.  Now this issue shows that "duplication" isn't the only problem.

**Comment by ulysses4ever** [comment]
To be clear, I meant even not having an “internal error” but a regular error instead would be a big  improvement, I think. Of course, fixing it is still better.

**Comment by boyland** [comment]
FYI: The internal error comes when the "where" clause system tries to print out what t should be mapped to.  Internally it (because of an error elsewhere) has the (understandable) idea that t needs to be mapped to an out-of-scope variable and then crashes trying to print this.

**Comment by boyland** [comment]
Fixed, and the more serious error underneath.

**Comment by ulysses4ever** [comment]
Great, glad to hear!
