### ISSUE TITLE
Permanent freeze on Save if .project (buildCommand) is invalid

### ISSUE THREAD

**Issue by ulysses4ever** [boyland/sasylf#109]
It seems something bad happened with 5af9f149: if I run on it, I can open the editor, I can make edits, but when I hit Ctrl+S to save edits, Eclipse freezes forever and I have to kill it. I tried it on a fresh virtual machine (Linux) and it perfectly reproduces. I have this behavior either when having plugin in dropins or when running it as an eclipse app. The previous commit works fine. The latest commit (currently) 5b50df0 suffers from the same problem for me.

**Comment by boyland** [comment]
That sounds terrible! Is that happening with all SLF files?  Or can you give me a test file where the freeze happens.

**Comment by boyland** [comment]
I wonder if somehow we get a loop in notifications some how?

**Comment by boyland** [comment]
If you run as an Eclipse app, see if you can use the debugger to find out where it's freezing.

**Comment by boyland** [comment]
I just pushed a few more commits: the latest one (https://github.com/boyland/sasylf/commit/488f7a8fed58ceb014ecb2f8c3a5702411bb05c1) tries to fix the problem (which I have not experienced).  Please try it out and let me know if it helps.  It seems the only place where the commit you pointed out could possibly cause a problem.

**Comment by ulysses4ever** [comment]
This is a loop most definitely. Works on any SLF I think. E.g. on the fresh handout for homework-12.  Running it with Debug instead of Run doesn't bring much insight to me: it just shows that a good bunch of threads are running, but there's nothing that seems helpful to diagnose.

Unfortunately, 488f7a8 doesn't seem to make any difference for me.

**Comment by ulysses4ever** [comment]
Okay, seems to be resolved by 488f7a8: cleaning is still hard to get right! It seems that running as an app didn't do the right thing. But with packaging and installing via dropins I can confirm that this commit works fine whereas the previous one loops.

**Comment by ulysses4ever** [comment]
This is funky: after trying the previous commit I can't make it work anymore with the latest one, and back to the square 1 where it hangs on Save. I don't understand it at all.

**Comment by ulysses4ever** [comment]
It seems to me it only happens for homework-12's `constraint.slf` specifically.

**Comment by boyland** [comment]
Weird.  Running with Debug as an Eclipse app would be helpful.  Try to find out which threads are stopped or livelocked (e.g. looping).  Check especially the SWT thread.  I don't get this behavior at all.  Maybe if you have extra time this evening, we could share screen.

**Comment by ulysses4ever** [comment]
As I said: debug does a lot of threads are running, and they don't seem to change when I hit Ctrl+S. I'm happy to screen-share but maybe not today: I'm feeling a bit weared out. We can do on Monday during office-hours maybe? (When are they? ;-))

**Comment by ulysses4ever** [comment]
Just to have the issue up to date: John figured that the reason for the freeze was a typo in the `.project` file: a wrong `<buildCommand>` was specified. The issue may make sense to keep open until a more user-friendly solution to this problem is implemented.

**Comment by boyland** [comment]
Deadlock possibility was commented in code.  Code now fixed to use a new technique (proxy creation rather than blocking).
