### ISSUE TITLE
paren matching has UI glitches

### ISSUE THREAD

**Issue by boyland** [boyland/sasylf#112]
In SASyLF 1.5.1a2 (and perhaps earlier releases), if under Java 14 or later, if one types something with brackets (and probably parens as well), e.g.
```
_ : G, x |- t[x] == t[x]
```
When the first `]` is typed, nothing shows, after the space, still nothing shows but when the `=` is typed, suddenly the closing brackets appears.  This problem does not happen with Java 11.

**Comment by boyland** [comment]
Yes, the same problem happens with parens.  
Also: the problem is windowing specific: if one types (say) `(x)x` and waits, the screen shows `(x  ` and no further changes happen indefinitely as long as one doesn't type anything, but if one switches to a different application, the text will appear. Even if one has a timed screen capture, just before the capture happens, the text is restored.  So it's hard to show a screenshot.

**Comment by boyland** [comment]
Got it with a screen recording.  Here, I've typed the same thing that's before the equal sign: `(x)x` and stopped. The second paren is just rendered as a space with a stray caret (cursor marker) that seems to be just covering most of the second `x` which is showing just the tips of its strokes on the right hand side.
![image](https://user-images.githubusercontent.com/1193683/125623634-0b625ab4-316a-40bf-b9a1-8e92b7b8eb63.png)

**Comment by boyland** [comment]
When I try to replicate this problem with the XML toy plugin with bracket matching added, the problem doesn't happen, but there is other behavior as well: the closing bracket is rendered *before* one types it, which behavior I've seen in Java too.  SASyLF doesn't do that in either 11, or 14.

**Comment by boyland** [comment]
I have verified that the bug exists in SASyLF 1.5.0 also.

**Comment by boyland** [comment]
...and it happens with Eclipse Photon (but again it must be run under Java 14 or later).

**Comment by boyland** [comment]
The problem happens with Eclipse 2021-03.  And with careful timing, I can get *three* carets in place at once:
![image](https://user-images.githubusercontent.com/1193683/125642806-a40f518b-0673-4f4a-abcc-94ece9809b3d.png)

**Comment by boyland** [comment]
Problem also happens in 2020-03.

**Comment by boyland** [comment]
Actually, I was able to replicate this problem with the toy XML editor.  The same behavior.  I have filed a bug with Eclipse.

**Comment by ulysses4ever** [comment]
@boyland could you share a link to your bug report against eclipse? I’m curious about this bug.

**Comment by boyland** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=574869

**Comment by boyland** [comment]
Eclipse has marked the bug fixed.  It expect the problem to be fixed in 2021-09.
