### ISSUE TITLE
Allow expressions inside [] when doing case analysis

### ISSUE THREAD

**Issue by JonathanAldrich** [boyland/sasylf#115]
SASyLF apparently allows only a single token inside []'s, i.e. [x] or [e].  This covers most cases, but we wrote a system for expressing integer constant propagation with a rule that substitutes #n (where n is a number and # embeds it in an expression) and can't case analyze with a case on that rule.  In particular if a rule has a e[#n] inside it then we get a parse error "expected ]" at the n.

(right now the file illustrating this is a homework solution so not posting publicly but can share privately, or come up with a proxy)

**Comment by boyland** [comment]
The issue as described is probably invalid, since the parser accepts more, but many uses of [.] lead to incomplete unification.  I'll close this for now, until we get a simple example that can be shared.
