### ISSUE TITLE
seemingly valid syntax sugar fails

### ISSUE THREAD

**Issue by lambduli** [boyland/sasylf#120]
Hi,
So I have the following definition

```
package plmts.proofs.ae;

terminals S Z a

syntax

n ::= Z
  | S n

AE ::=  "(" + AE AE ")"
    |   "(" * AE AE ")"
    |   n

0 := Z
```

The line with `0 := Z` causes this error: `multiple syntactic case(s) or judgment(s) [(Z), Z]`.

Weirdly enough, it only fails if I have the definition of `AE` here. But I don't see what is wrong with it. It seems to be working on its own just fine, only when I want to define a couple of useful aliases it breaks.

Please let me know if there is something wrong with what I am doing. Thank you very much for your efforts!

**Comment by boyland** [comment]
Here the error message is correct. "Z" could either refer to something of type n or of type AE.  if you change your AE grammar to add a symbol, it will remove the ambiguity.
```
AE := ...
      | # n
```

**Comment by lambduli** [comment]
Oh, I see. Thanks a lot!
