### ISSUE TITLE
RFE: value declarations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [boyland/sasylf#25]
```
For various reasons, it would be nice to have a way to declare values, e.g.

   1 :=: S 0

or

   null :=: ptr(0)

This would make for better clarity (like named constants) and
this sort of thing needed if/when we add modules.

```

Original issue reported on code.google.com by `boyland....@gmail.com` on 20 Jan 2012 at 3:47

**Comment by boyland** [comment]
The syntax supported uses `:=` rather than `:=:`.  The change also supports sugar with arguments, e.g.
 
    (SUCC n) := S n
