### ISSUE TITLE
Line comments on multiple premises cause errors - SASyLF sees the lines flow together

### ISSUE THREAD

**Issue by JoshuaSCochrane** [boyland/sasylf#67]
```
t1 ⇓ false // This comment gives: Error: Cannot parse any 
// syntactic case or judgment for expression t1 ⇓ false t3 ⇓ t3'
t3 ⇓ t3'
--------------------------- B-IfFalse
if t1 then t2 else t3 ⇓ t3'
```

Block comments or line comments with a blank line following are accepted (or I guess even 'excepted' here; see also http://www.xkcd.com/326/):
```
t1 ⇓ false /* This comment is ok */
t3 ⇓ t3' // duplicate judgment for effect; this one's ok w/ blank line:

t3 ⇓ t3' // so is this one (not the exception mentioned above; always ok on the last line)
--------------------------- B-IfFalse
if t1 then t2 else t3 ⇓ t3'
```

Not hard to avoid with block comments where necessary, but maybe it's easy to fix anyway...

**Comment by boyland** [comment]
This is a feature, not a bug.  Use // to stich together multiple lines.  Use /* ... */ if you don't want to do so.  The documentation on the Wiki indicates that.
