### ISSUE TITLE
Quick-fix adding judgments to previous 'contradiction' does not convert to case analysis

### ISSUE THREAD

**Issue by JoshuaSCochrane** [boyland/sasylf#70]
At one point I had `proof by contradiction on i`, but then realized I was missing some judgments. When I added those judgments, SASyLF correctly indicated the contradiction was missing cases. Quick-fix offered to insert them, but it left it as `contradiction` when it did so, causing check errors. It would be better for quick-fix to convert to case analysis when cases are added to contradictions.

**Comment by boyland** [comment]
Yes, that's a bug.
