### ISSUE TITLE
Quick-fix "or" judgment with new name chooses a fresh name rather than reuse existing new name.

### ISSUE THREAD

**Issue by JoshuaSCochrane** [boyland/sasylf#71]
E.g. SASyLF starts at `t0`, but Pierce usually starts at `t1`. Renaming a quick-fix-generated\* `t0` to a `t1` and then doing further quick-fix generation re-uses `t0` again, causing check errors. I don't see the help/mouseover text being incorrect now, but I'm pretty sure we saw that behavior in class at some point.

e.g.:

```
 case rule // T-Succ
    t1n: t1 : Nat // renamed generated t0 to t1 to match book
    ------------------ T-Succ
    _: (succ t1) : Nat
  is
    ti: t1 value or t1 -> t1' by induction hypothesis on t1n
    proof by case analysis on ti:
      case or tv: t1 value is // BUG: SASyLF still puts t0 here
        t1v: t1 value : Nat by lemma canonical-forms on t1n,tv
        t1nv: t1 numvalue by inversion of canonical-num on t1v
        tnv: t numvalue by rule numval-succ on t1nv
        _: t value by rule val-num on tnv
      end case
      case or te: t1 -> t1' is // BUG: SASyLF still puts t0 here
        _: t -> t' by rule E-Succ on te
      end case
    end case analysis
  end case
```

*not entirely sure it needs to be quick-fix-generated, but that was my experience

**Comment by boyland** [comment]
There is a bug here, but it's not on the first case (which will correctly use t1) but the second in which the quick-fix will use t0 (or any free variable) instead of t1'.

**Comment by boyland** [comment]
This was fixed when fixing Sean's bug, shown in good37.slf
a6a55ba5909cdaaebf64faa9cb2ace31dcbadaa1
