### ISSUE TITLE
Second-level quick-fix did not pick a unique name for context

### ISSUE THREAD

**Issue by JoshuaSCochrane** [boyland/sasylf#72]
When doing T-Var/var analysis to prove unique typing, the first quick-fix generated application of the var rule used `Gamma'`, and then the second quick-fix generated application also used `Gamma'` and caused a check error "`Context already in use: Gamma'`". Changing it to `Gamma''` fixed this, but quick-fix shouldn't generate errors.

I don't think any other auto-generated variables were renamed or anything, so I'm not sure if this is different from #71 or not.

(This is testable with my homework6 file by deleting the second `case rule var`)

**Comment by boyland** [comment]
This is indeed a bug.

**Comment by boyland** [comment]
Hmm.  The problem is sometimes a quick fix error.
