### ISSUE TITLE
Quick-fix to fill "or" cases renames them incorrectly

### ISSUE THREAD

**Issue by xalles** [boyland/sasylf#73]
Sometimes, when using quick-fix in Eclipse to fill in **or** cases, the names used in the supplied cases don't match the original **or** derivation, and SASyLF errors ensue. Quick-fix should just copy the parts of the **or** derivation verbatim. An example of the error is below. (The actual proof has been commented out.)

![sasylf or case issue](https://cloud.githubusercontent.com/assets/8594325/20163732/5d39c4a6-a6c4-11e6-9d63-54adc9f83e86.jpg)

**Comment by boyland** [comment]
Duplicates Issue #71
