### ISSUE TITLE
Saving in Eclipse checks with SASyLF, but does not add code folding

### ISSUE THREAD

**Issue by xalles** [boyland/sasylf#75]
Saving in Eclipse with the plugin automatically checks the saved slf file with SASyLF, which is nice, but for some reason code folding is not activated by saving alone. Folding is only activated after checking the code explicitly, either with CTRL-0 or by clicking the green check button.

**Comment by boyland** [comment]
Fixed in today's SASyLF hackathon with Kayla Rodenbeck and Amir Hesamian
