### ISSUE TITLE
SASyLF version 1.4.1a1 - where clause of use inversion complains about direction of the rebindings

### ISSUE THREAD

**Issue by kanatos92** [boyland/sasylf#84]
With command line option --compwhere, following are a few examples of the error message

	syntax
	t ::= 1 | t + t
	
	judgment eq: t = t
	
	----- eq
	t = t
	
	theorem A:
	    forall p: t = t'
	    exists t' = t.
            // use inversion of rule eq on p where t':= t
	    // complains about "Missing where clause for: t"
	    // so it has to be:
	    use inversion of rule eq on p where t:= t'
	    proof by rule eq
	end theorem
	
	theorem B:
	    forall p: t1 + t2 = t1' + t2'
	    exists t1 = t1'.
	    // use inversion of rule eq on p where t1:= t1' and t2:=t2'
	    // complains about "Missing where clauses for: t2', t1'"
	    // this works:
	    use inversion of rule eq on p where t1':= t1 and t2':=t2
	    proof by rule eq
	end theorem

	theorem C:
	    forall p: (t1 + t2) + t3 = (t1' + t2') + t3'
	    exists t1 = t1'.
	    // use inversion of rule eq on p where t1:= t1' and t2:=t2' and t3:=t3'
	    // complains about "Missing where clause for: t3'"
	    // use inversion of rule eq on p where t1':= t1 and t2':=t2 and t3':=t3
	    // complains about "Missing where clauses for: t1, t2"
	    // this works:
	    use inversion of rule eq on p where t1:= t1' and t2:=t2' and t3':=t3
	    proof by rule eq
	end theorem
	
	theorem D:
	    forall p: ((t1 + t2) + t3) + t4 = ((t1' + t2') + t3') + t4'
	    exists t1 = t1'.
            // use inversion of rule eq on p where t1:= t1' and t2:=t2' and t3:=t3' and t4:=t4'
	    // complains about "Missing where clauses for: t4', t2', t1'"
	    // this works
	    use inversion of rule eq on p where t1':= t1 and t2':=t2 and t3:=t3' and t4':=t4
	    proof by rule eq
	end theorem
	
	theorem D2:
	    forall p: (t1 + t2) + (t3 + t4) = (t1' + t2') + (t3' + t4')
	    exists t1 = t1'.
	    // this works:
	    use inversion of rule eq on p where t1:= t1' and t2:=t2' and t3:=t3' and t4:=t4'
	    proof by rule eq
	end theorem

**Comment by boyland** [comment]
Thanks.  Yes, this is a bug. "use inversion" works badly with where clauses; we have found other cases:
```
theorem gt-anti-refl:
  forall n
  forall d: n > n 
  exists contradiction .
  use inversion of rule gt-more on d
    where n := s n'
  p: n' > n' by theorem succ-cancels-gt on n', d
  proof by induction hypothesis on n', p
end theorem
```
And even with regular inversion:
```
theorem gt-anti-reflexive:
  forall n
  forall d: n > n 
  exists contradiction .
  _: n' > n by inversion of rule gt-more on d
    where n := s n'
  p: n' > n' by theorem succ-cancels-gt on n', d
  proof by induction hypothesis on n', p
end theorem
```
The "inversion" above is accepted if `n'  >  n` is replaced with `n' > s n'`

**Comment by boyland** [comment]
Original bug test cases (good42.slf) pass now.  Closing bug for now (while leaving more specific errors in good40.slf).
