### ISSUE TITLE
[feature request] Eclipse TODO-based Tasks

### ISSUE THREAD

**Issue by ulysses4ever** [boyland/sasylf#94]
Eclipse has special support for comments containing `TODO`: they will normally (e.g. in Java perspective) show up in the _Tasks_ view. It doesn't seem to be the case for SASyLF. It'd be nice to have this work.

**Comment by boyland** [comment]
Still looking to find out how to do this in Eclipse.

**Comment by mlhaufe** [comment]
@boyland In my experience this is terribly complicated.

When I did this for my [thesis](https://github.com/thenewobjective/versioned-lexical-search/blob/master/eclipse-plugin/edu.uwm.cs599.versioned-lexical-search/src/edu/uwm/cs599/versionedlexicalsearch/views/QueryResults.java) I followed:

<https://www.vogella.com/tutorials/EclipseJFaceTable/article.html>

**Comment by boyland** [comment]
I think I have to declare the new marker type in the plugin.xml as a subtype of IMarker.TASK and it might just work.  Then I have to generate the markers. Working on it.

**Comment by boyland** [comment]
Eventually the specific tags should be customizable.  But for now, what tags would you like?  TODO, XXX and FIX are the ones I'm starting with.

**Comment by ulysses4ever** [comment]
Sure, those sound good. A form of FIX that I'm more used to is FIXME, but that's no big deal.

**Comment by boyland** [comment]
Actually you're right FIXME is the proper thing.  Will do.
