### ISSUE TITLE
 [feature request] Eclipse shortcut for block comment

### ISSUE THREAD

**Issue by ulysses4ever** [boyland/sasylf#95]
In Java sources, you can do `Ctrl+/` to comment out highlighted lines. It'd be nice to have the same in `*.slf` files.

**Comment by ulysses4ever** [comment]
So, there's a problem with 1cb3bfe: unlike in Java, double `Ctrl+/` don't get you to back the initial state, and instead, adds two layers of `//`. I'd go as far as claiming that this would be barely useful in the present form, unfortunately.

**Comment by boyland** [comment]
I wasn't sure what the convention was.  Some modes used control-\ to remove comments, so that's what I did.  Have you tried it?

**Comment by ulysses4ever** [comment]
Oh, this works, thanks! This is a little less obvious to me but fine, I guess.
