### ISSUE TITLE
Order of error messages reversed

### ISSUE THREAD

**Issue by ulysses4ever** [boyland/sasylf#96]
It seems that the order of error messages is always reversed: I see errors pertaining to the later positions in the file above the ones concerned with the earlier positions. It shouldn't be hard and would be beneficial imo to reverse the order to make it top-down.

**Comment by ulysses4ever** [comment]
Actually, it seems it's not always the case but sometimes. Which makes me think it can be harder to fix…

**Comment by boyland** [comment]
The line is often to the "end" of the syntactic structure where the error was found.  Getting them in order would require buffering all error messages and sorting.  I don't think I will fix.
