### ISSUE TITLE
[docs] The Contributing section in README?

### ISSUE THREAD

**Issue by ulysses4ever** [boyland/sasylf#98]
It would be nice to have some tips for those who would be interested in improving SASyLF. This is usually done by the means "Contributing" section in README.md, which could include: 0) Are 3-rd party contributions even welcome :-), 1) What it takes to set up a development environment (what plugins of Eclipse required to develop this plugin), 2) the preferred way to submit patches (I assume PR to this GH repo).

**Comment by boyland** [comment]
Fixed!
